### ISSUE TITLE
Remove dependency on use_frameworks! in IOS Podfile

### ISSUE THREAD

**Issue by billnbell** [forcedotcom/SalesforceMobileSDK-Package#260] opened 2022-08-08 05:56 UTC
In your Podfile it requires use_frameworks for some reason. This is not good for React Native 0.69.3. The main reason is react-native-maps, react-native-video, and @react-native-firebase/* and several other super popular packages do not work under use_frameworks.  React Native has deprecated use of use_frameworks since 0.68+. I have no idea how to fix this to work without use_frameworks, but I think your team should work on it. Then this library will be super useful for sure.

I heard there might be a static solution for these 2 libraries. Using something like: https://github.com/joncardasis/cocoapods-user-defined-build-types - but I tried a bunch of things and cannot get all to work. Maybe you could try RNFirebase and Maps?

```
platform :ios, '14.0'
use_frameworks!
```

**Comment by wmathurin** [comment] 2022-09-06 17:53
We will take a look.
Closing this issue since it's a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/252

**Closed by wmathurin** 2022-09-06 17:53 UTC
