### ISSUE TITLE
Salesforce created React Project not Runing 

### ISSUE THREAD

**Issue by Umesh079** [forcedotcom/SalesforceMobileSDK-Package#220] opened 2020-12-25 07:08 UTC
Hello Team,

I am facing issue in creating project using forcereact. I have tried many a time constantly receiving erros.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SFQuerySpec", referenced from:
      objc-class-ref in SFSmartStoreReactBridge.o
  "_OBJC_CLASS_$_SFSoupIndex", referenced from:
      objc-class-ref in SFSmartStoreReactBridge.o
  "_OBJC_CLASS_$_SFSDKDevAction", referenced from:
      objc-class-ref in SalesforceReactSDKManager.o
  "_OBJC_CLASS_$_SFSoupSpec", referenced from:
      objc-class-ref in SFSmartStoreReactBridge.o
  "_OBJC_CLASS_$_SalesforceSDKManager", referenced from:
      objc-class-ref in SFOauthReactBridge.o
  "_RCTRegisterModule", referenced from:
      +[SFMobileSyncReactBridge load] in SFMobileSyncReactBridge.o
      +[SFNetReactBridge load] in SFNetReactBridge.o
      +[SFOauthReactBridge load] in SFOauthReactBridge.o
      +[SFSmartStoreReactBridge load] in SFSmartStoreReactBridge.o
  "_OBJC_CLASS_$_SFUserAccountManager", referenced from:
      objc-class-ref in SFOauthReactBridge.o
  "_kSFNotificationUserDidLogout", referenced from:
      -[SFOauthReactBridge logoutCurrentUser:callback:] in SFOauthReactBridge.o
  "_OBJC_CLASS_$_SFStoreCursor", referenced from:
      objc-class-ref in SFSmartStoreReactBridge.o
  "_OBJC_CLASS_$_SFRestRequest", referenced from:
      objc-class-ref in SFNetReactBridge.o
  "_RCTMakeError", referenced from:
      -[SFMobileSyncReactBridge getSyncStatus:callback:] in SFMobileSyncReactBridge.o
      -[SFMobileSyncReactBridge deleteSync:callback:] in SFMobileSyncReactBridge.o
      -[SFMobileSyncReactBridge syncDown:callback:] in SFMobileSyncReactBridge.o
      -[SFMobileSyncReactBridge reSync:callback:] in SFMobileSyncReactBridge.o
      -[SFMobileSyncReactBridge cleanResyncGhosts:callback:] in SFMobileSyncReactBridge.o
      -[SFMobileSyncReactBridge syncUp:callback:] in SFMobileSyncReactBridge.o
      -[SFMobileSyncReactBridge handleCleanReSyncGhosts:numRecords:callback:] in SFMobileSyncReactBridge.o
      ...
  "_OBJC_CLASS_$_SFSmartStore", referenced from:
      objc-class-ref in SFMobileSyncReactBridge.o
      objc-class-ref in SFSmartStoreReactBridge.o
     (maybe you meant: _OBJC_CLASS_$_SFSmartStoreReactBridge)
  "_OBJC_CLASS_$_SFRestAPI", referenced from:
      objc-class-ref in SFNetReactBridge.o
  "_kDefaultSmartStoreName", referenced from:
      -[SFMobileSyncReactBridge storeName:] in SFMobileSyncReactBridge.o
      -[SFSmartStoreReactBridge storeName:] in SFSmartStoreReactBridge.o
      -[SFSmartStoreReactBridge internalCursorId:withGlobal:andStoreName:] in SFSmartStoreReactBridge.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation).

**1. I have already tried removing and readding POD file.
2. Tried reinstalling project**

I am using 

**Salesforce react 8.3.0
Xcode 12.3**

I have tried on original react native without salesforce and it is working .
<img width="694" alt="Screen Shot 2020-12-25 at 12 31 44 PM" src="https://user-images.githubusercontent.com/30233097/103124481-e5958500-46ad-11eb-8ea5-3af0263188bf.png">
<img width="868" alt="Screen Shot 2020-12-25 at 12 37 22 PM" src="https://user-images.githubusercontent.com/30233097/103124489-f1814700-46ad-11eb-84c3-ad6a526323b6.png">

**Comment by bhariharan** [comment] 2020-12-25 17:35
@Umesh079 This is a duplicate of [this issue](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/209). We have addressed this as a part of [this PR](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/212), which will be a part of `Mobile SDK 9.0`. Meanwhile, you should be able to get it working using `Xcode 11`.

**Closed by bhariharan** 2020-12-25 17:35 UTC

**Comment by Umesh079** [comment] 2020-12-26 04:54
Thank you @bhariharan
